services:
  pg-module-one:
    image: postgres:16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: module-one-db
    ports:
      - 5432:5432
    volumes:
      - module-one-tripdata:/var/lib/postgresql/data
    networks:
      - network-module-one
  
  pgadmin-module-one:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 8085:80
    volumes:
      - module-one-pgadmin:/var/lib/pgadmin
    networks:
      - network-module-one
    depends_on:
      - pg-module-one

networks:
  network-module-one:

volumes:
  module-one-tripdata:
  module-one-pgadmin: